### ISSUE TITLE
Create spell-checking solution

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/runbook#10]
This would ideally be:
- something in Python (since that's a dependency we already have)
- in a format which can also be read by various editors
- checked on CI

**Comment by RealOrangeOne** [comment]
We have a spellchecker on https://github.com/srobo/team-emails, which works _kinda_ well. The dictionary isn't great, and it's written in node, and has no editor integration. 

I remember looking for ones in Python, but found very little. Alternatively, I suspect it won't be that difficult to write one if we really needed one.

**Comment by PeterJCLaw** [comment]
Fixed by https://github.com/srobo/runbook/pull/140
