### ISSUE TITLE
Add automatic link checking

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/runbook#12]
While `mkdocs` tries to catch broken internal links, it doesn't seem to completely succeed. It would be great if we could catch broken links during CI.

Note: if there are options to `mkdocs` to make this stricter/fail more loudly that we're missing, that's a viable (and probably the best) solution.

**Comment by RealOrangeOne** [comment]
I believe mkdocs raises a warning when it finds a link like this. The repo is setup to abort if any warnings are raised, which should cover this. We should do some proper testing to ensure this actually works, though.

**Comment by PeterJCLaw** [comment]
Hrm, https://github.com/mkdocs/mkdocs/issues/192#issuecomment-352325894 hints that to get the automatic validation we should have our links end with `.md`, which I'd not realised (I think I may have stripped out the `.md`s when merging the historic stuff.

**Comment by PeterJCLaw** [comment]
Since the fix to #17, I think this is now about as well sorted as we can get without adding something of our own on top. I realise this issue was originally about doing that, however the value that adds is fairly limited now we've got `mkdocs` doing most of the checking.

Closing this as no longer useful, though happy to be disagreed with if there's a strong feeling we need something more.
