### ISSUE TITLE
Create general guidelines for the Core Team

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/runbook#52]
It would be very useful to those taking on a leadership role (currently referred to as the Core Team) to have some guidance about how best to perform that role.

We have some docs on the specifics (and that collection will grow as we document more experiences), but we don't have much around how the team should operate. While we don't want to tie the hands of that team, it is useful for them to know ahead of time what has worked well in the past, where the pitfalls and gotchas are, as well as guidance on the scale of things.

**Comment by PeterJCLaw** [comment]
Some initial thoughts on this, based on various (not all SR) experiences:
- Establish a regular cadence of _short_ meetings of the Core Team. The goal of these should be semi-formalised *very high level* progress check-ins to keep on track, provide an opportunity to unblock things, get input on challenges and raise concerns. Be aware that these meetings inherently exclude others, so should focus on things which either only the Core Team can do or which (for whatever reason) _must_ remain their direct responsibility. (For clarity: things which merely _happen_ to be their direct responsibility don't count)
- Establish a regular cadence of updates to volunteers. The goal here is to provide a way for volunteers to jump in to ongoing things and to celebrate achievements.
- Establish a canonical task tracker. (Be aware that https://github.com/srobo/tasks/issues exists, so if you're going to do something else then do so as early as possible and make it clear what and why)
- Encourage input from a wide team of volunteers. While mass emails can work, you'll also need to approach people individually about things. Try to meet new volunteers in person as much as possible - it's _much_ easier to work remotely with people you've met in person and this also helps build trust which allows you to more easily work through misunderstandings.
- Use the existing documentation. If you've found these docs, then you're already doing well, if not then how are you reading this‽
- Update the documentation. The existing docs are guidelines, not rules. The best way to help your future selves (and ensure you understand the thing you're working on) is to improve the docs. Note that the docs include a task list for running the competition -- use that too!
- Kick-off projects. At the start of a project or task, ensure that those who are going to be doing the work understand what's involved and that everyone has a clear picture of what a good outcome looks like. I realise this totally sounds like corporate management rubbish, but repeated personal experience shows it's totally worth doing. (meta note: I'm planning to write a blog post on this soon™)

**Comment by trickeydan** [comment]
Thoughts on expanding scope of this issue to all teams?

**Comment by PeterJCLaw** [comment]
Sure. There's probably going to be things here which are more applicable to teams which re-form each year, though even then that might apply to when new members join existing teams.
