### ISSUE TITLE
Vanity URL

### ISSUE THREAD

**Issue by trickeydan** [srobo/runbook#58]
Recently, the Ops Manual has moved to https://opsmanual.studentrobotics.org/

It would be nice to match that, e.g https://runbook.studentrobotics.org/

Also, that is much easier to explain to somebody than srobo.github.io/runbook.

It may also help with #17

**Comment by RealOrangeOne** [comment]
In the past, SR has used almost solely path-based app routing `/forum/`, `/cgit/` etc etc. 

I don't think I mind too much whether it's path-based or subdomain-based, but I think we need to be standardising

Personally I prefer subdomain-based.

**Comment by trickeydan** [comment]
> I don't think I mind too much whether it's path-based or subdomain-based, but I think we need to be consistent.

I personally favour subdomains, but either way we're currently inconsistent.

I suspect it may be worth asking the trustees what other things are setup with subdomains, and making a decision with them about where we want things to be, so that it is consistent.

**Comment by PeterJCLaw** [comment]
Originally SR had subdomains for everything (git.srobo.org, ide.srobo.org, trac.srobo.org). Around the time the new website (i.e: https://github.com/srobo/website) was deployed the majority of those were dropped.
Some do still work, though they've had a spotty history of being broken by various things.

I think we're currently biased in favour of most things being on the root domain (e.g: srobo.org/docs) and probably makes sense to keep most things that way unless there's a good reason to change them back again.

**Comment by richardbarlow** [comment]
It's worth noting that the only reason why the ops manual ended up as subdomain is that GitBook recently grew the ability to just that. From a maintainability point of view it's significantly easier as it only requires DNS configuration. If you want to have it path based then an HTTP server somewhere also needs configuration.

**Comment by RealOrangeOne** [comment]
I was inclined to try and match convention, but it seems `mkdocs` doesn't easily support being hosted from a path.

I've added PRs to add `runbook.studentrobotics.org` as the runbook domain (https://github.com/srobo/runbook/pull/64 & https://github.com/srobo/infrastructure/pull/6)
